"""Baseline schema, as of the initial commit.

Deliberately **excludes** the audit hash-chain columns, which revision
``0002_audit_chain`` adds. That split is what lets a database created before the
chain existed be brought forward rather than recreated: it is stamped at this
revision and then upgraded. A fresh database runs both in order and ends in the
same place.

Original autogenerate message: baseline schema

Revision ID: d952889bcd2f
Revises: 
Create Date: 2026-09-19 10:48:22.833095
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# The schema uses custom column types from this module; autogenerate emits
# their qualified names without the import.
import iluvtrade.db.base  # noqa: F401


revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('personal_for_user_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organizations_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'SUSPENDED', 'DELETED', name='userstatus', native_enum=False), nullable=False),
    sa.Column('live_trading_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('audit_events',
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('actor_user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    )
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_events_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_actor_user_id'), ['actor_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_events_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index('ix_audit_org_created', ['organization_id', 'created_at'], unique=False)

    op.create_table('broker_accounts',
    sa.Column('broker', sa.Enum('PAPER', 'ZERODHA', name='brokerkind', native_enum=False), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('venue_account_id', sa.String(length=120), nullable=True),
    sa.Column('venue_user_name', sa.String(length=200), nullable=True),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'broker', 'label', name='uq_broker_acct')
    )
    with op.batch_alter_table('broker_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_accounts_organization_id'), ['organization_id'], unique=False)

    op.create_table('creator_payouts',
    sa.Column('period_start', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('period_end', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('gross_amount', sa.String(length=40), nullable=False),
    sa.Column('platform_fee', sa.String(length=40), nullable=False),
    sa.Column('net_amount', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('purchase_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('settled_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('rating_snapshot', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_payouts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_payouts_organization_id'), ['organization_id'], unique=False)

    op.create_table('data_sources',
    sa.Column('kind', sa.Enum('UPLOAD', 'HTTP', name='sourcekind', native_enum=False), nullable=False),
    sa.Column('origin', sa.String(length=2000), nullable=False),
    sa.Column('requested_uri', sa.String(length=2000), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=200), nullable=True),
    sa.Column('retrieved_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('raw_path', sa.String(length=500), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_data_sources_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_data_sources_organization_id'), ['organization_id'], unique=False)

    op.create_table('datasets',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_dataset_slug')
    )
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_datasets_organization_id'), ['organization_id'], unique=False)

    op.create_table('memberships',
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'TRADER', 'ADMIN', 'OWNER', name='role', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'user_id', name='uq_membership')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memberships_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memberships_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'ERROR', 'CRITICAL', name='notificationseverity', native_enum=False), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('read_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_org_created', ['organization_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('sessions',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('strategies',
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Enum('PRIVATE', 'ORGANIZATION', 'MARKETPLACE', name='strategyvisibility', native_enum=False), nullable=False),
    sa.Column('owner_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_strategy_slug')
    )
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategies_organization_id'), ['organization_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('plan', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('TRIALING', 'ACTIVE', 'PAST_DUE', 'CANCELLED', name='subscriptionstatus', native_enum=False), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('current_period_end', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_organization_id'), ['organization_id'], unique=False)

    op.create_table('broker_connections',
    sa.Column('broker_account_id', sa.String(length=36), nullable=False),
    sa.Column('state', sa.Enum('DISCONNECTED', 'AUTHORIZING', 'CONNECTED', 'EXPIRED', 'ERROR', 'REVOKED', name='connectionstate', native_enum=False), nullable=False),
    sa.Column('encrypted_credentials', sa.LargeBinary(), nullable=True),
    sa.Column('credential_hint', sa.String(length=40), nullable=True),
    sa.Column('token_expires_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('connected_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('authorization_attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('broker_account_id')
    )
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_broker_connections_organization_id'), ['organization_id'], unique=False)

    op.create_table('dataset_versions',
    sa.Column('dataset_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'REJECTED', 'FAILED', name='datasetversionstatus', native_enum=False), nullable=False),
    sa.Column('schema_json', sa.Text(), nullable=False),
    sa.Column('quality_json', sa.Text(), nullable=False),
    sa.Column('transformations_json', sa.Text(), nullable=False),
    sa.Column('cleaning_policy_json', sa.Text(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('rejected_row_count', sa.Integer(), nullable=False),
    sa.Column('symbol_count', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.Float(), nullable=True),
    sa.Column('end_timestamp', sa.Float(), nullable=True),
    sa.Column('inferred_frequency', sa.String(length=32), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('canonical_path', sa.String(length=500), nullable=True),
    sa.Column('canonical_hash', sa.String(length=64), nullable=True),
    sa.Column('approved_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('approved_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['data_sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_id', 'version', name='uq_dataset_version')
    )
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_versions_dataset_id'), ['dataset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_versions_organization_id'), ['organization_id'], unique=False)

    op.create_table('listings',
    sa.Column('slug', sa.String(length=140), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.String(length=400), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('methodology', sa.Text(), nullable=False),
    sa.Column('risk_disclosure', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'VALIDATING', 'SUBMITTED', 'APPROVED', 'PUBLISHED', 'REJECTED', 'WITHDRAWN', name='listingstatus', native_enum=False), nullable=False),
    sa.Column('price_amount', sa.String(length=40), nullable=False),
    sa.Column('price_currency', sa.String(length=8), nullable=False),
    sa.Column('billing_cadence', sa.Enum('ONE_TIME', 'MONTHLY', 'ANNUAL', name='billingcadence', native_enum=False), nullable=False),
    sa.Column('version_access_policy', sa.Enum('PINNED', 'ROLLING', name='versionaccesspolicy', native_enum=False), nullable=False),
    sa.Column('licence_terms', sa.Text(), nullable=False),
    sa.Column('supported_brokers_json', sa.Text(), nullable=False),
    sa.Column('supported_instruments_json', sa.Text(), nullable=False),
    sa.Column('supported_data_json', sa.Text(), nullable=False),
    sa.Column('published_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_listing_slug')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('strategy_versions',
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'DEPRECATED', name='strategyversionstatus', native_enum=False), nullable=False),
    sa.Column('implementation_key', sa.String(length=120), nullable=False),
    sa.Column('parameters_schema_json', sa.Text(), nullable=False),
    sa.Column('default_parameters_json', sa.Text(), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('published_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('published_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('certification_status', sa.Enum('UNCERTIFIED', 'PENDING', 'CERTIFIED', 'REJECTED', name='certificationstatus', native_enum=False), nullable=False),
    sa.Column('certification_notes', sa.Text(), nullable=False),
    sa.Column('frozen', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('strategy_id', 'version', name='uq_strategy_version')
    )
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_strategy_versions_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_strategy_versions_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('backtest_jobs',
    sa.Column('submitted_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus', native_enum=False), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('queued_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('started_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('cancel_requested_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_code', sa.String(length=64), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'idempotency_key', name='uq_backtest_idempotency')
    )
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_jobs_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_jobs_submitted_by_user_id'), ['submitted_by_user_id'], unique=False)

    op.create_table('listing_versions',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_backtest_run_id', sa.String(length=36), nullable=True),
    sa.Column('release_notes', sa.Text(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'strategy_version_id', name='uq_listing_version')
    )
    with op.batch_alter_table('listing_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_versions_listing_id'), ['listing_id'], unique=False)

    op.create_table('purchases',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('purchased_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PAID', 'FAILED', 'REFUNDED', name='purchasestatus', native_enum=False), nullable=False),
    sa.Column('amount', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('platform_fee', sa.String(length=40), nullable=False),
    sa.Column('creator_net', sa.String(length=40), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('provider_reference', sa.String(length=200), nullable=True),
    sa.Column('licence_hash', sa.String(length=64), nullable=False),
    sa.Column('idempotency_key', sa.String(length=80), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_idempotency_key'), ['idempotency_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchases_organization_id'), ['organization_id'], unique=False)

    op.create_table('reviews',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('author_user_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'organization_id', name='uq_review_once')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviews_organization_id'), ['organization_id'], unique=False)

    op.create_table('trading_sessions',
    sa.Column('mode', sa.Enum('PAPER', 'LIVE', name='tradingmode', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'STARTING', 'RUNNING', 'PAUSED', 'STOPPING', 'STOPPED', 'FAILED', 'HALTED', name='sessionstatus', native_enum=False), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('entitlement_id', sa.String(length=36), nullable=True),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=True),
    sa.Column('broker_account_id', sa.String(length=36), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('risk_config_json', sa.Text(), nullable=False),
    sa.Column('starting_cash', sa.String(length=40), nullable=False),
    sa.Column('base_currency', sa.String(length=8), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('live_confirmed_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('live_confirmed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('kill_switch_engaged', sa.Boolean(), nullable=False),
    sa.Column('kill_switch_reason', sa.String(length=400), nullable=True),
    sa.Column('started_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('last_advanced_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('cash', sa.String(length=40), nullable=True),
    sa.Column('equity', sa.String(length=40), nullable=True),
    sa.Column('realized_pnl', sa.String(length=40), nullable=True),
    sa.Column('unrealized_pnl', sa.String(length=40), nullable=True),
    sa.Column('commission_paid', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['broker_account_id'], ['broker_accounts.id'], ),
    sa.ForeignKeyConstraint(['dataset_version_id'], ['dataset_versions.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['strategy_version_id'], ['strategy_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trading_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trading_sessions_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_sessions_mode'), ['mode'], unique=False)
        batch_op.create_index(batch_op.f('ix_trading_sessions_organization_id'), ['organization_id'], unique=False)

    op.create_table('backtest_runs',
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_version_id', sa.String(length=36), nullable=False),
    sa.Column('dataset_canonical_hash', sa.String(length=64), nullable=True),
    sa.Column('strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_content_hash', sa.String(length=64), nullable=True),
    sa.Column('parameters_json', sa.Text(), nullable=False),
    sa.Column('universe_json', sa.Text(), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('engine_name', sa.String(length=64), nullable=False),
    sa.Column('engine_version', sa.String(length=32), nullable=False),
    sa.Column('records_processed', sa.Integer(), nullable=False),
    sa.Column('order_count', sa.Integer(), nullable=False),
    sa.Column('fill_count', sa.Integer(), nullable=False),
    sa.Column('starting_cash', sa.String(length=40), nullable=False),
    sa.Column('ending_equity', sa.String(length=40), nullable=False),
    sa.Column('realized_pnl', sa.String(length=40), nullable=False),
    sa.Column('unrealized_pnl', sa.String(length=40), nullable=False),
    sa.Column('commission_paid', sa.String(length=40), nullable=False),
    sa.Column('total_return', sa.Float(), nullable=True),
    sa.Column('cagr', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe_ratio', sa.Float(), nullable=True),
    sa.Column('max_drawdown', sa.Float(), nullable=True),
    sa.Column('artifact_path', sa.String(length=500), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['backtest_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id')
    )
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_runs_organization_id'), ['organization_id'], unique=False)

    op.create_table('entitlements',
    sa.Column('listing_id', sa.String(length=36), nullable=False),
    sa.Column('strategy_id', sa.String(length=36), nullable=False),
    sa.Column('granted_strategy_version_id', sa.String(length=36), nullable=False),
    sa.Column('version_access_policy', sa.Enum('PINNED', 'ROLLING', name='versionaccesspolicy', native_enum=False), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'REVOKED', name='entitlementstatus', native_enum=False), nullable=False),
    sa.Column('source_purchase_id', sa.String(length=36), nullable=True),
    sa.Column('valid_from', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('valid_until', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=400), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_strategy_version_id'], ['strategy_versions.id'], ),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_purchase_id'], ['purchases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entitlements_listing_id'), ['listing_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entitlements_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entitlements_strategy_id'), ['strategy_id'], unique=False)

    op.create_table('session_events',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.create_index('ix_session_event', ['session_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_events_organization_id'), ['organization_id'], unique=False)

    op.create_table('session_fills',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('engine_fill_id', sa.String(length=64), nullable=False),
    sa.Column('engine_order_id', sa.String(length=64), nullable=False),
    sa.Column('instrument', sa.String(length=120), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('price', sa.String(length=40), nullable=False),
    sa.Column('commission', sa.String(length=40), nullable=False),
    sa.Column('fill_timestamp', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_fills', schema=None) as batch_op:
        batch_op.create_index('ix_session_fill', ['session_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_fills_engine_fill_id'), ['engine_fill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_fills_engine_order_id'), ['engine_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_fills_organization_id'), ['organization_id'], unique=False)

    op.create_table('session_orders',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('engine_order_id', sa.String(length=64), nullable=False),
    sa.Column('broker_order_id', sa.String(length=120), nullable=True),
    sa.Column('instrument', sa.String(length=120), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('filled_quantity', sa.String(length=40), nullable=False),
    sa.Column('average_fill_price', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('order_type', sa.String(length=24), nullable=False),
    sa.Column('submitted_timestamp', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_orders', schema=None) as batch_op:
        batch_op.create_index('ix_session_order', ['session_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_orders_engine_order_id'), ['engine_order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_orders_organization_id'), ['organization_id'], unique=False)

    op.create_table('session_positions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('instrument', sa.String(length=120), nullable=False),
    sa.Column('quantity', sa.String(length=40), nullable=False),
    sa.Column('average_price', sa.String(length=40), nullable=False),
    sa.Column('market_price', sa.String(length=40), nullable=True),
    sa.Column('unrealized_pnl', sa.String(length=40), nullable=True),
    sa.Column('realized_pnl', sa.String(length=40), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['trading_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('session_positions', schema=None) as batch_op:
        batch_op.create_index('ix_session_position', ['session_id', 'instrument'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_positions_organization_id'), ['organization_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_positions_organization_id'))
        batch_op.drop_index('ix_session_position')

    op.drop_table('session_positions')
    with op.batch_alter_table('session_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_orders_organization_id'))
        batch_op.drop_index(batch_op.f('ix_session_orders_engine_order_id'))
        batch_op.drop_index('ix_session_order')

    op.drop_table('session_orders')
    with op.batch_alter_table('session_fills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_fills_organization_id'))
        batch_op.drop_index(batch_op.f('ix_session_fills_engine_order_id'))
        batch_op.drop_index(batch_op.f('ix_session_fills_engine_fill_id'))
        batch_op.drop_index('ix_session_fill')

    op.drop_table('session_fills')
    with op.batch_alter_table('session_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_session_events_kind'))
        batch_op.drop_index('ix_session_event')

    op.drop_table('session_events')
    with op.batch_alter_table('entitlements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entitlements_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_entitlements_organization_id'))
        batch_op.drop_index(batch_op.f('ix_entitlements_listing_id'))

    op.drop_table('entitlements')
    with op.batch_alter_table('backtest_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_runs_organization_id'))

    op.drop_table('backtest_runs')
    with op.batch_alter_table('trading_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trading_sessions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_trading_sessions_mode'))
        batch_op.drop_index(batch_op.f('ix_trading_sessions_created_by_user_id'))

    op.drop_table('trading_sessions')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_organization_id'))
        batch_op.drop_index(batch_op.f('ix_reviews_listing_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_organization_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_listing_id'))
        batch_op.drop_index(batch_op.f('ix_purchases_idempotency_key'))

    op.drop_table('purchases')
    with op.batch_alter_table('listing_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_versions_listing_id'))

    op.drop_table('listing_versions')
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_submitted_by_user_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_organization_id'))

    op.drop_table('backtest_jobs')
    with op.batch_alter_table('strategy_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategy_versions_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_strategy_versions_organization_id'))

    op.drop_table('strategy_versions')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_strategy_id'))
        batch_op.drop_index(batch_op.f('ix_listings_organization_id'))

    op.drop_table('listings')
    with op.batch_alter_table('dataset_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_versions_organization_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_versions_dataset_id'))

    op.drop_table('dataset_versions')
    with op.batch_alter_table('broker_connections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_connections_organization_id'))

    op.drop_table('broker_connections')
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_organization_id'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('strategies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_strategies_organization_id'))

    op.drop_table('strategies')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_token_hash'))

    op.drop_table('sessions')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_organization_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_kind'))
        batch_op.drop_index('ix_notification_org_created')

    op.drop_table('notifications')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memberships_user_id'))
        batch_op.drop_index(batch_op.f('ix_memberships_organization_id'))

    op.drop_table('memberships')
    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_datasets_organization_id'))

    op.drop_table('datasets')
    with op.batch_alter_table('data_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_data_sources_organization_id'))
        batch_op.drop_index(batch_op.f('ix_data_sources_content_hash'))

    op.drop_table('data_sources')
    with op.batch_alter_table('creator_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_payouts_organization_id'))

    op.drop_table('creator_payouts')
    with op.batch_alter_table('broker_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_broker_accounts_organization_id'))

    op.drop_table('broker_accounts')
    with op.batch_alter_table('audit_events', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_org_sequence')
        batch_op.drop_index('ix_audit_org_created')
        batch_op.drop_index(batch_op.f('ix_audit_events_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_organization_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_event_hash'))
        batch_op.drop_index(batch_op.f('ix_audit_events_actor_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_events_action'))

    op.drop_table('audit_events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('organizations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organizations_slug'))

    op.drop_table('organizations')
    # ### end Alembic commands ###
