"""Record the correlation id of the request that queued a backtest.

Nullable, so existing jobs keep working: a job queued before this revision has
no originating trace, and inventing one would be worse than admitting it.

Original autogenerate message: backtest correlation id

Revision ID: da0fff6c060d
Revises: 0002_audit_chain
Create Date: 2026-09-19 11:20:21.242352
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# The schema uses custom column types from this module; autogenerate emits
# their qualified names without the import.
import iluvtrade.db.base  # noqa: F401


revision: str = '0003_correlation_id'
down_revision: str | None = '0002_audit_chain'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correlation_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_backtest_jobs_correlation_id'), ['correlation_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('backtest_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_jobs_correlation_id'))
        batch_op.drop_column('correlation_id')

    # ### end Alembic commands ###
