"""Two-factor authentication state on a user.

Every column is nullable or defaulted, so existing accounts are unaffected: MFA
is off until a user enrols. ``mfa_secret`` holds the TOTP secret under the same
AES-GCM envelope as a broker credential — it is a credential, and a database
disclosure of it would let an attacker mint valid codes indefinitely.

Original autogenerate message: mfa

Revision ID: 8842244731c9
Revises: 0003_correlation_id
Create Date: 2026-09-19 15:20:42.567007
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# The schema uses custom column types from this module; autogenerate emits
# their qualified names without the import.
import iluvtrade.db.base  # noqa: F401


revision: str = '0004_mfa'
down_revision: str | None = '0003_correlation_id'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("mfa_secret", sa.LargeBinary(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "mfa_enabled_at", iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True
            )
        )
        batch_op.add_column(sa.Column("mfa_last_counter", sa.Integer(), nullable=True))
        # Added **nullable** and tightened below. SQLite cannot add a NOT NULL
        # column to a table that already has rows unless a default is supplied,
        # and its DDL is not transactional — so the autogenerated
        # ``nullable=False`` form failed partway through, leaving two columns
        # added and the revision unrecorded. Three steps instead of one.
        batch_op.add_column(sa.Column("mfa_recovery_hashes", sa.Text(), nullable=True))

    op.execute(
        sa.text("UPDATE users SET mfa_recovery_hashes = '[]' "
                "WHERE mfa_recovery_hashes IS NULL")
    )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.alter_column(
            "mfa_recovery_hashes",
            existing_type=sa.Text(),
            nullable=False,
            server_default=sa.text("'[]'"),
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('mfa_last_counter')
        batch_op.drop_column('mfa_recovery_hashes')
        batch_op.drop_column('mfa_enabled_at')
        batch_op.drop_column('mfa_secret')

    # ### end Alembic commands ###
