"""Invitations and password-reset tokens.

Two new tables and nothing else — no column is added to a populated table, so
the trap that half-applied ``0004_mfa`` on SQLite (a NOT NULL column with no
server default, under non-transactional DDL) does not arise here. That is worth
stating rather than leaving to inspection: the check to make on any migration
touching this schema is "does it alter an existing table", and the answer here
is no.

``invitations`` is organization-scoped: an invitation is an offer of membership
in exactly one workspace. ``password_reset_tokens`` is deliberately **not** —
a password belongs to a person, who may be a member of several organizations,
and scoping it would force a meaningless choice of tenant.

Neither table stores a usable secret. Both hold an HMAC of the token under the
application secret, exactly as ``sessions.token_hash`` does, so reading either
table yields nothing that can be presented.

Revision ID: 0005_teams_and_reset
Revises: 0004_mfa
Create Date: 2026-09-19 16:06:02.101083
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# The schema uses custom column types from this module; autogenerate emits
# their qualified names without the import.
import iluvtrade.db.base  # noqa: F401


revision: str = '0005_teams_and_reset'
down_revision: str | None = '0004_mfa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('VIEWER', 'TRADER', 'ADMIN', 'OWNER', name='role', native_enum=False), nullable=False),
    sa.Column('invited_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('accepted_user_id', sa.String(length=36), nullable=True),
    sa.Column('revoked_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash', name='uq_invitation_token')
    )
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.create_index('ix_invitation_org_email', ['organization_id', 'email'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_invitations_token_hash'), ['token_hash'], unique=False)

    op.create_table('password_reset_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', iluvtrade.db.base.UtcDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_reset_tokens_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token_hash'))

    op.drop_table('password_reset_tokens')
    with op.batch_alter_table('invitations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitations_token_hash'))
        batch_op.drop_index(batch_op.f('ix_invitations_organization_id'))
        batch_op.drop_index('ix_invitation_org_email')

    op.drop_table('invitations')
    # ### end Alembic commands ###
